version: '3'
services:

  web:
    container_name: server
    image: suucong2877/damoacon
    expose:
      - 8080
    restart: always
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    image: suucong2877/nginx
    ports:
      - 80:80
    depends_on:
      - server